name: Tag and Release
on:
  pull_request:
    branches: [ main ]
    types: [closed]
  workflow_dispatch:
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: code-checkout
        uses: actions/checkout@v2

      - name: Bump version and push tag
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.base.ref == 'main'
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main, master

      - name: Create a GitHub release
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.base.ref == 'main'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}